Repository sparta-onetoone/sparta-onetoone, pull requests merged in 2025-02, with the labels that each got.

#9 공통 모듈 및 패키지 생성
  build.gradle
  src/main/java/com/eureka/spartaonetoone/common/client/.gitkeep
  src/main/java/com/eureka/spartaonetoone/common/config/JpaAuditingConfig.java
  src/main/java/com/eureka/spartaonetoone/common/config/QueryDslConfig.java
  src/main/java/com/eureka/spartaonetoone/common/config/SecurityConfig.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/.gitkeep
  src/main/java/com/eureka/spartaonetoone/common/exception/CustomException.java
  src/main/java/com/eureka/spartaonetoone/common/utils/CommonResponse.java
  src/main/java/com/eureka/spartaonetoone/common/utils/TimeStamp.java
  src/main/java/com/eureka/spartaonetoone/domain/.gitkeep
Labels: ⚙ setting

#10 CustomException 생성
  src/main/java/com/eureka/spartaonetoone/common/exception/CustomException.java
  src/main/java/com/eureka/spartaonetoone/common/exception/CustomExceptionHandler.java
Labels: ⚙ setting

#12 Timestamp 오류 수정 & .gitignore 오타 수정
  .gitignore
  src/main/java/com/eureka/spartaonetoone/common/utils/TimeStamp.java
Labels: 🔧 fix

#47 도메인들 간 통신을 위해 사용하는 PaymentClient 개발
  src/main/java/com/eureka/spartaonetoone/common/client/PaymentClient.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/PaymentRequest.java
  src/main/java/com/eureka/spartaonetoone/domain/payment/application/dtos/PaymentSearchDto.java
  src/main/java/com/eureka/spartaonetoone/domain/payment/domain/repository/CustomPaymentRepository.java
  src/main/java/com/eureka/spartaonetoone/domain/payment/infrastructure/PaymentRepositoryImpl.java
  src/main/java/com/eureka/spartaonetoone/domain/payment/presentation/PaymentController.java
  src/main/java/com/eureka/spartaonetoone/payment/application/PaymentService.java
  src/main/java/com/eureka/spartaonetoone/payment/application/dtos/PaymentCreateRequestDto.java
  src/main/java/com/eureka/spartaonetoone/payment/application/dtos/PaymentGetResponseDto.java
  src/main/java/com/eureka/spartaonetoone/payment/application/dtos/PaymentSearchRequestDto.java
  src/main/java/com/eureka/spartaonetoone/payment/application/exception/PaymentException.java
  src/main/java/com/eureka/spartaonetoone/payment/domain/Payment.java
  src/main/java/com/eureka/spartaonetoone/payment/domain/repository/CustomPaymentRepository.java
  src/main/java/com/eureka/spartaonetoone/payment/domain/repository/PaymentRepository.java
  src/main/java/com/eureka/spartaonetoone/payment/infrastructure/PaymentRepositoryImpl.java
  src/main/java/com/eureka/spartaonetoone/payment/presentation/PaymentController.java
Labels: ✏ feat, 🛠 refactor

#54 주문 관련 기능 구현
  src/main/java/com/eureka/spartaonetoone/common/client/CartClient.java
  src/main/java/com/eureka/spartaonetoone/common/client/PaymentClient.java
  src/main/java/com/eureka/spartaonetoone/common/client/ProductClient.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/.gitkeep
  src/main/java/com/eureka/spartaonetoone/common/dtos/request/PaymentRequest.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/request/ProductRequest.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/response/CartResponse.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/response/ProductResponse.java
  src/main/java/com/eureka/spartaonetoone/order/application/OrderService.java
  src/main/java/com/eureka/spartaonetoone/order/application/dtos/OrderItemInfo.java
  src/main/java/com/eureka/spartaonetoone/order/application/dtos/request/OrderCreateRequestDto.java
  src/main/java/com/eureka/spartaonetoone/order/application/dtos/response/OrderCreateResponseDto.java
  src/main/java/com/eureka/spartaonetoone/order/application/dtos/response/OrderSearchResponseDto.java
  src/main/java/com/eureka/spartaonetoone/order/application/exceptions/OrderException.java
  src/main/java/com/eureka/spartaonetoone/order/domain/Order.java
  src/main/java/com/eureka/spartaonetoone/order/domain/OrderItem.java
  src/main/java/com/eureka/spartaonetoone/order/domain/OrderStatus.java
  src/main/java/com/eureka/spartaonetoone/order/domain/OrderType.java
  src/main/java/com/eureka/spartaonetoone/order/domain/repository/OrderRepository.java
  src/main/java/com/eureka/spartaonetoone/order/presentation/OrderController.java
  src/main/java/com/eureka/spartaonetoone/payment/presentation/PaymentController.java
Labels: ✏ feat

#58 WebClient 인증 문제 해결
  src/main/java/com/eureka/spartaonetoone/auth/config/JwtSecurityFilter.java
  src/main/java/com/eureka/spartaonetoone/cart/application/CartService.java
  src/main/java/com/eureka/spartaonetoone/cart/application/dtos/request/CartCreateRequestDto.java
  src/main/java/com/eureka/spartaonetoone/cart/application/dtos/request/CartItemCreateRequestDto.java
  src/main/java/com/eureka/spartaonetoone/cart/application/exceptions/CartItemException.java
  src/main/java/com/eureka/spartaonetoone/cart/domain/Cart.java
  src/main/java/com/eureka/spartaonetoone/cart/domain/CartItem.java
  src/main/java/com/eureka/spartaonetoone/common/client/ProductClient.java
  src/main/java/com/eureka/spartaonetoone/common/config/WebClientConfig.java
  src/main/java/com/eureka/spartaonetoone/user/domain/User.java
  src/main/java/com/eureka/spartaonetoone/user/infrastructure/security/UserDetailsImpl.java
  src/test/java/com/eureka/spartaonetoone/cart/application/CartServiceTest.java
  src/test/java/com/eureka/spartaonetoone/cart/domain/repository/CartRepositoryTest.java
  src/test/java/com/eureka/spartaonetoone/cart/presentation/CartControllerTest.java
Labels: ✏ feat, 🔧 fix, 🐞 bug

#63 테스트에 사용될 가상의 mock 인증 객체를 구현
  build.gradle
  src/main/java/com/eureka/spartaonetoone/user/domain/User.java
  src/main/java/com/eureka/spartaonetoone/user/infrastructure/security/UserDetailsImpl.java
  src/test/java/com/eureka/spartaonetoone/mock/MockUser.java
  src/test/java/com/eureka/spartaonetoone/mock/WithSecurityContextFactoryImpl.java
Labels: ✏ feat, 📋 test

#64 상품 통합, 단위 테스트 구현
  src/main/java/com/eureka/spartaonetoone/common/dtos/request/ProductRequest.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/response/ProductResponse.java
  src/main/java/com/eureka/spartaonetoone/product/application/ProductService.java
  src/main/java/com/eureka/spartaonetoone/product/application/dtos/request/ProductCreateRequestDto.java
  src/main/java/com/eureka/spartaonetoone/product/application/dtos/request/ProductReduceRequestDto.java
  src/main/java/com/eureka/spartaonetoone/product/application/dtos/request/ProductSearchRequestDto.java
  src/main/java/com/eureka/spartaonetoone/product/application/dtos/request/ProductUpdateRequestDto.java
  src/main/java/com/eureka/spartaonetoone/product/application/dtos/response/ProductGetResponseDto.java
  src/main/java/com/eureka/spartaonetoone/product/domain/Product.java
  src/test/java/com/eureka/spartaonetoone/product/application/ProductServiceTest.java
  src/test/java/com/eureka/spartaonetoone/product/integration/ProductIntegrationTest.java
  src/test/java/com/eureka/spartaonetoone/product/presentation/ProductControllerTest.java
Labels: 📋 test, 🛠 refactor

#68 Auditing 오류 수정
  src/main/java/com/eureka/spartaonetoone/common/config/JpaAuditingConfig.java
  src/main/java/com/eureka/spartaonetoone/common/utils/UserAuditorAware.java
Labels: 🔧 fix, 🐞 bug

#66 주문 관련 기능 및 테스트
  src/main/java/com/eureka/spartaonetoone/cart/application/dtos/CartItemInfo.java
  src/main/java/com/eureka/spartaonetoone/common/client/OrderClient.java
  src/main/java/com/eureka/spartaonetoone/common/config/WebClientConfig.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/response/CartResponse.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/response/OrderResponse.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/response/ProductResponse.java
  src/main/java/com/eureka/spartaonetoone/order/application/OrderService.java
  src/main/java/com/eureka/spartaonetoone/order/application/dtos/request/OrderCreateRequestDto.java
  src/main/java/com/eureka/spartaonetoone/order/application/dtos/request/OrderRequestDto.java
  src/main/java/com/eureka/spartaonetoone/order/application/dtos/response/OrderCancelRequestDto.java
  src/main/java/com/eureka/spartaonetoone/order/application/dtos/response/OrderCreateResponseDto.java
  src/main/java/com/eureka/spartaonetoone/order/application/exceptions/OrderException.java
  src/main/java/com/eureka/spartaonetoone/order/domain/Order.java
  src/main/java/com/eureka/spartaonetoone/order/domain/OrderItem.java
  src/main/java/com/eureka/spartaonetoone/order/domain/repository/OrderRepository.java
  src/main/java/com/eureka/spartaonetoone/order/presentation/OrderController.java
  src/main/resources/application-test.yml
  src/test/java/com/eureka/spartaonetoone/order/application/OrderServiceTest.java
  src/test/java/com/eureka/spartaonetoone/order/presentation/OrderControllerTest.java
Labels: ✏ feat, 📋 test

#69 TimeStamp 클래스의 수정자, 생성자, 삭제자 자료형을 수정
  src/main/java/com/eureka/spartaonetoone/common/utils/TimeStamp.java
  src/main/java/com/eureka/spartaonetoone/payment/application/dtos/PaymentGetResponseDto.java
Labels: 🔧 fix, 🐞 bug

#73 Dockerfile 생성 및 오류 수정
  Dockerfile
  build.gradle
  src/main/java/com/eureka/spartaonetoone/user/infrastructure/security/UserDetailsImpl.java
Labels: ✏ feat, 🔧 fix

#76 Swagger 설정 및 주문, 장바구니 Swagger 구현
  build.gradle
  src/main/java/com/eureka/spartaonetoone/cart/application/CartService.java
  src/main/java/com/eureka/spartaonetoone/cart/application/dtos/response/CartSearchResponseDto.java
  src/main/java/com/eureka/spartaonetoone/cart/domain/Cart.java
  src/main/java/com/eureka/spartaonetoone/cart/domain/CartItem.java
  src/main/java/com/eureka/spartaonetoone/cart/presentation/CartApi.java
  src/main/java/com/eureka/spartaonetoone/cart/presentation/CartController.java
  src/main/java/com/eureka/spartaonetoone/common/config/SecurityConfig.java
  src/main/java/com/eureka/spartaonetoone/common/config/SwaggerConfig.java
  src/main/java/com/eureka/spartaonetoone/order/presentation/OrderApi.java
  src/main/java/com/eureka/spartaonetoone/order/presentation/OrderController.java
  src/main/resources/application-test.yml
  src/test/java/com/eureka/spartaonetoone/cart/application/CartServiceTest.java
  src/test/java/com/eureka/spartaonetoone/cart/domain/repository/CartRepositoryTest.java
  src/test/java/com/eureka/spartaonetoone/cart/presentation/CartControllerTest.java
Labels: ✏ feat, ⚙ setting

#77 결제내역에 대한 접근을 ROLE에 따라 분기하는 설정을 추가하였음
  src/main/java/com/eureka/spartaonetoone/common/client/OrderClient.java
  src/main/java/com/eureka/spartaonetoone/common/client/StoreClient.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/response/OrderResponse.java
  src/main/java/com/eureka/spartaonetoone/common/dtos/response/StoreResponse.java
  src/main/java/com/eureka/spartaonetoone/payment/application/PaymentService.java
  src/main/java/com/eureka/spartaonetoone/payment/application/exception/PaymentException.java
  src/main/java/com/eureka/spartaonetoone/payment/infrastructure/PaymentRepositoryImpl.java
  src/main/java/com/eureka/spartaonetoone/payment/presentation/PaymentController.java
  src/test/java/com/eureka/spartaonetoone/mock/MockUser.java
  src/test/java/com/eureka/spartaonetoone/payment/application/PaymentServiceTest.java
  src/test/java/com/eureka/spartaonetoone/payment/integration/PaymentIntegrationTest.java
  src/test/java/com/eureka/spartaonetoone/payment/presentation/PaymentControllerTest.java
Labels: ✏ feat, 📋 test, 🛠 refactor

#84 resources 패키지 생성 및 readme 수정
  README.md
  src/main/resources/.gitkeep
Labels: 📄 docs, 🔧 fix, 🐞 bug
